service: manga-scrapper-project
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  stage: production
  region: ap-southeast-1
  runtime: nodejs16.x
  memorySize: 512
  timeout: 30

functions:
  api:
    handler: handler.handler
    environment:
      API_URL: ${env:API_URL}
      API_KEY: ${env:API_KEY}
      API_HOST: ${env:API_HOST}
    events:
      - httpApi: '*'
