service: mangaScraper

frameworkVersion: '3'

custom:
  prod:
    Stack: mangaScraper
    LogLevel: info
    MangaTableRCU: 10
    MangaTableWCU: 10
  dev:
    Stack: mangaScraper
    LogLevel: debug
    MangaTableRCU: 1
    MangaTableWCU: 1

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-1
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: 14
  environment:
    logLevel: ${self:custom.${self:provider.stage}.LogLevel}

package:
  individually: true

functions:
  Root:
    handler: src/_root/index.handler
    memorySize: 128
    timeout: 10
    events:
      - http:
          path: /
          method: get
          cors: true
  Scraper:
    handler: src/scraper/index.handler
    layers:
      - arn:aws:lambda:${aws:region}:764866452798:layer:chrome-aws-lambda:31
    memorySize: 2048
    timeout: 20
    environment:
      region: ${aws:region}
      mangaTable: ${self:custom.${self:provider.stage}.Stack}-mangaTable-${self:provider.stage}
      scraperQueueUrl: https://sqs.${aws:region}.amazonaws.com/${aws:accountId}/${self:custom.${self:provider.stage}.Stack}-scraperQueue-${self:provider.stage}
    iam:
      role:
        statements:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:UpdateItem
            Resource:
              - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.${self:provider.stage}.Stack}-mangaTable-${self:provider.stage}
          - Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource:
              - arn:aws:sqs:${aws:region}:${aws:accountId}:table/${self:custom.${self:provider.stage}.Stack}-scraperQueue-${self:provider.stage}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ScraperQueue
              - Arn
          batchSize: 1

resources:
  - ${file(resources/apigateway/RestApi.yml)}
  - ${file(resources/dynamodb/MangaTable.yml)}
  - ${file(resources/sqs/ScraperQueue.yml)}
  - Outputs:
      ApiGWRestApiId:
        Value:
          Ref: ApiGatewayRestApi
        Export:
          Name: ${self:custom.${self:provider.stage}.Stack}-restApiId-${self:provider.stage}
      ApiGWRootResourceId:
        Value:
          Fn::GetAtt:
            - ApiGatewayRestApi
            - RootResourceId
        Export:
          Name: ${self:custom.${self:provider.stage}.Stack}-rootResourceId-${self:provider.stage}

plugins:
  - serverless-iam-roles-per-function
  - serverless-plugin-reducer
