service: mangaScraper-api-series

frameworkVersion: '3'

custom:
  prod:
    Stack: mangaScraper
    LogLevel: info
  dev:
    Stack: mangaScraper
    LogLevel: debug

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 128
  timeout: 10
  region: ap-southeast-1
  stage: ${opt:stage, 'dev'}
  apiGateway:
    restApiId:
      Fn::ImportValue: ${self:custom.${self:provider.stage}.Stack}-restApiId-${self:provider.stage}
    restApiRootResourceId:
      Fn::ImportValue: ${self:custom.${self:provider.stage}.Stack}-rootResourceId-${self:provider.stage}
  logRetentionInDays: 14
  environment:
    logLevel: ${self:custom.${self.provider.stage}.LogLevel}

package:
  individually: true

functions:
  Series:
    handler: index.handler
    iam:
      role:
        statements:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Query
            Resource:
              - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.${self:provider.stage}.Stack}-mangaTable-${self:provider.stage}
          - Effect: Allow
            Action:
              - sqs:SendMessage
            Resource:
              - arn:aws:sqs:${aws:region}:${aws:accountId}:${self:custom.${self:provider.stage}.Stack}-scraperQueue-${self:provider.stage}
    events:
      - http:
          path: /series
          method: get
          cors: true
      - http:
          path: /series
          method: post
          cors: true
      - http:
          path: /series/{seriesId}
          method: get
          cors: true
      - http:
          path: /series/{seriesId}/chapters
          method: get
          cors: true
      - http:
          path: /series/{seriesId}/chapters
          method: post
          cors: true

plugins:
  - serverless-iam-roles-per-function
  - serverless-plugin-reducer
