app: manga-scraper
org: tigaron
service: mangaScraper-api-series

frameworkVersion: '3'

custom:
  reducer:
    ignoreMissing: true
  prod:
    Stack: mangaScraper
    LogLevel: info
  dev:
    Stack: mangaScraper
    LogLevel: debug

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 128
  timeout: 10
  region: ap-southeast-1
  stage: ${opt:stage, 'dev'}
  apiGateway:
    restApiId:
      Fn::ImportValue: ${self:custom.${self:provider.stage}.Stack}-restApiId-${self:provider.stage}
    restApiRootResourceId:
      Fn::ImportValue: ${self:custom.${self:provider.stage}.Stack}-rootResourceId-${self:provider.stage}
  logRetentionInDays: 14
  environment:
    logLevel: ${self:custom.${self:provider.stage}.LogLevel}

package:
  individually: true

functions:
  Series:
    handler: index.handler
    environment:
      region: ${aws:region}
      mangaTable: ${self:custom.${self:provider.stage}.Stack}-mangaTable-${self:provider.stage}
      scraperQueueUrl: https://sqs.${aws:region}.amazonaws.com/${aws:accountId}/${self:custom.${self:provider.stage}.Stack}-ScraperQueue-${self:provider.stage}.fifo
    iamRoleStatementsName: ${self:service}-${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:GetItem
          - dynamodb:Query
        Resource:
          - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.${self:provider.stage}.Stack}-mangaTable-${self:provider.stage}
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource:
          - arn:aws:sqs:${aws:region}:${aws:accountId}:${self:custom.${self:provider.stage}.Stack}-ScraperQueue-${self:provider.stage}.fifo
    events:
      - http:
          path: /series
          method: get
          cors: true
      - http:
          path: /series
          method: post
          cors: true
      - http:
          path: /series/{id}
          method: get
          cors: true
      - http:
          path: /series/{id}
          method: post
          cors: true

resources:
  Outputs:
    ApiRootSeries:
      Value:
        Ref: ApiGatewayResourceSeries
      Export:
        Name: ${self:custom.${self:provider.stage}.Stack}-ApiRootSeries-${self:provider.stage}
    ApiRootSeriesIdVar:
      Value:
        Ref: ApiGatewayResourceSeriesIdVar
      Export:
        Name: ${self:custom.${self:provider.stage}.Stack}-ApiRootSeriesIdVar-${self:provider.stage}

plugins:
  - serverless-iam-roles-per-function
  - serverless-plugin-common-excludes
  - serverless-plugin-reducer
