org: tigaron
app: manga-scraper
service: MangaScraper-Scraper

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-1
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: 14
  iam:
    role:
      name: IAM-${self:service}-${sls:stage}
      path: /${self:service}-${sls:stage}/
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource:
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.stack}-SeriesTable-${sls:stage}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.stack}-ChapterTable-${sls:stage}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.stack}-StatusTable-${sls:stage}
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            - arn:aws:sqs:${aws:region}:${aws:accountId}:${self:custom.stack}-ScraperQueue-${sls:stage}.fifo
  environment:
    region: ${aws:region}
    logLevel: ${self:custom.${sls:stage}.LogLevel}
    scraperQueueUrl: https://sqs.${aws:region}.amazonaws.com/${aws:accountId}/${self:custom.stack}-ScraperQueue-${sls:stage}.fifo
    seriesTable: ${self:custom.stack}-SeriesTable-${sls:stage}
    chapterTable: ${self:custom.stack}-ChapterTable-${sls:stage}
    statusTable: ${self:custom.stack}-StatusTable-${sls:stage}

package:
  individually: true
  patterns:
    - '!*.test.js'

layers:
  Chrome:
    name: ${self:custom.stack}-Chrome-${self:provider.stage}
    description: '@sparticuz/chrome-aws-lambda'
    package:
      artifact: ../../resources/lambda/chrome-aws-lambda.zip

functions:
  Scraper:
    handler: index.handler
    layers:
      - !Ref ChromeLambdaLayer
    name: ${self:service}-${sls:stage}
    description: Scraper service to update webtoons and chapters database
    memorySize: 2048
    timeout: 900
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ ScraperQueue, Arn ]
          batchSize: 1

resources:
  - ${file(../../resources/sqs/ScraperQueue.yml)}
  - ${file(../../resources/dynamodb/SeriesTable.yml)}
  - ${file(../../resources/dynamodb/ChapterTable.yml)}
  - ${file(../../resources/dynamodb/StatusTable.yml)}

plugins:
  - serverless-plugin-monorepo
  - serverless-plugin-common-excludes
  - serverless-offline

custom:
  stack: MangaScraper
  prod:
    LogLevel: info
    TableRCU: 10
    TableWCU: 10
  dev:
    LogLevel: debug
    TableRCU: 1
    TableWCU: 1
  enterprise:
    collectLambdaLogs: false
    disableAwsSpans: true
    disableHttpSpans: true
