Resources:
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.${self:provider.stage}.Stack}-DeadLetterQueue-${self:provider.stage}.fifo
      FifoQueue: true
      ContentBasedDeduplication: false
      DelaySeconds: 0
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 1209600
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 170
  ScraperQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.${self:provider.stage}.Stack}-ScraperQueue-${self:provider.stage}.fifo
      FifoQueue: true
      ContentBasedDeduplication: false
      DelaySeconds: 0
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 1209600
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt:
            - DeadLetterQueue
            - Arn
        maxReceiveCount: 10
      VisibilityTimeout: 170
