org: tigaron
app: manga-scraper
service: MangaScraper-Api-Series

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-1
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: 14
  iam:
    role:
      name: IAM-${self:service}-${sls:stage}
      path: /${self:service}-${sls:stage}/
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource:
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.stack}-StatusTable-${sls:stage}
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:Query
          Resource:
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.stack}-SeriesTable-${sls:stage}
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource:
            - arn:aws:sqs:${aws:region}:${aws:accountId}:${self:custom.stack}-ScraperQueue-${sls:stage}.fifo
  apiGateway:
    restApiId:
      Fn::ImportValue: ${self:custom.stack}-RestApiId-${sls:stage}
    restApiRootResourceId:
      Fn::ImportValue: ${self:custom.stack}-RootResourceId-${sls:stage}
  environment:
    region: ${aws:region}
    logLevel: ${self:custom.${sls:stage}.LogLevel}
    seriesTable: ${self:custom.stack}-SeriesTable-${sls:stage}
    statusTable: ${self:custom.stack}-StatusTable-${sls:stage}
    scraperQueueUrl:
      Fn::ImportValue: ${self:custom.stack}-ScraperQueueUrl-${sls:stage}

package:
  individually: true
  patterns:
    - '!*.test.js'

functions:
  Series:
    handler: index.handler
    name: ${self:service}-${sls:stage}
    description: Endpoint for webtoon's series
    memorySize: 1024
    timeout: 10
    events:
      - http:
          path: /series
          method: get
      - http:
          path: /series
          method: post
      - http:
          path: /series/{id}
          method: get
      - http:
          path: /series/{id}
          method: post

resources:
  Outputs:
    AGResourceSeries:
      Value:
        Ref: ApiGatewayResourceSeries
      Export:
        Name: ${self:custom.stack}-ResourceSeriesId-${sls:stage}
    AGResourceSeriesIdVar:
      Value:
        Ref: ApiGatewayResourceSeriesIdVar
      Export:
        Name: ${self:custom.stack}-ResourceSeriesIdVar-${sls:stage}

plugins:
  - serverless-plugin-monorepo
  - serverless-plugin-common-excludes
  - serverless-offline

custom:
  stack: MangaScraper
  prod:
    LogLevel: info
  dev:
    LogLevel: debug
  enterprise:
    collectLambdaLogs: false
