service: mangaScraper-api-__SERVICE__

frameworkVersion: '3'

custom:
  prod:
    Stack: mangaScraper
    LogLevel: info
  dev:
    Stack: mangaScraper
    LogLevel: debug

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 128
  timeout: 10
  region: ap-southeast-1
  stage: ${opt:stage, 'dev'}
  apiGateway:
    restApiId:
      Fn::ImportValue: ${self:custom.${self:provider.stage}.Stack}-restApiId-${self:provider.stage}
    restApiRootResourceId:
      Fn::ImportValue: ${self:custom.${self:provider.stage}.Stack}-rootResourceId-${self:provider.stage}
  logRetentionInDays: 14
  environment:
    logLevel: ${self:custom.${self:provider.stage}.LogLevel}

functions:
  __FUNCTION__:
    handler: index.handler
    events:
      - http:
          path: /__PATH__
          method: get
          cors: true

plugins:
  - serverless-iam-roles-per-function
